# vim:fileencoding=utf-8:foldmethod=marker
# symbol_map
env read_from_shell=EDITOR

background_opacity 1

font_size 14
disable_ligatures cursor

# cursor #cccccc
# cursor_text_color #111111

cursor_shape block
cursor_shape_unfocused hollow
cursor_beam_thickness 1.5
cursor_blink_interval 1.5 linear linear
cursor_stop_blinking_after 1000.0
cursor_trail 50
cursor_trail_decay 0.1 0.2
cursor_trail_start_threshold 8
# cursor_trail_color #888888
confirm_os_window_close 0

tab_bar_edge bottowm
tab_bar_min_tabs 2
tab_bar_style powerline
tab_bar_background #151515

active_tab_foreground   #000
active_tab_background   #8844e0
active_tab_font_style   bold-italic
inactive_tab_foreground #666
inactive_tab_background #222
inactive_tab_font_style normal

scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

# url_color #0087bd
url_style curly
open_url_with default
show_hyperlink_targets true
underline_hyperlinks hover
paste_actions no-op

repaint_delay 20
input_delay 10

enable_audio_bell no
window_alert_on_bell yes
bell_on_tab "🔔 "

initial_window_width 60c
initial_window_height 20c

hide_window_decorations no

remember_window_size no
remember_window_position no

window_resize_step_cells 2
window_resize_step_lines 2
# foreground #dddddd
background #151515

shell_integration enabled

allow_remote_control yes

# NVIM GUARD
map --when-focus-on 'not title:neovim and not title:History' ctrl+j scroll_line_down
map --when-focus-on 'not title:neovim and not title:History' ctrl+k scroll_line_up
map --when-focus-on 'not title:neovim and not title:History' ctrl+shift+j scroll_to_prompt 1
map --when-focus-on 'not title:neovim and not title:History' ctrl+shift+k scroll_to_prompt -1
map --when-focus-on 'not title:neovim and not title:History' ctrl+m show_scrollback
# clear scrollback buffer
map --when-focus-on 'not title:neovim and not title:History' ctrl+shift+l send_text normal printf \'\\033[2J\\033[3J\\033[1;1H\'\x0d

map ctrl+shift+m kitty_shell window
map ctrl+shift+n send_text normal,arguments \x01\x0b ${EDITOR-vi} ~/.config/kitty/kitty.conf\r
map ctrl+tab next_tab

# BEGIN_KITTY_FONTS
font_family      family="CaskaydiaMono Nerd Font Mono"
bold_font        family='CaskaydiaMono Nerd Font Mono' style=Bold
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
