require("skc.commands.autocommands.bwipeout_on_delete")
require("skc.commands.autocommands.cd_on_enter_dir")
require("skc.commands.autocommands.highlight_on_yank")
require("skc.commands.autocommands.kittynvim")
require("skc.commands.autocommands.treesitter")
